Employee/Employee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('emp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Employee/emp/urls.py
from django.urls import path
from . import views

app_name = 'emp'

urlpatterns = [
    path('',views.employee_list,name='employee_list'),
    path('create_employee/',views.employee_create,name='employee_create'),
    path('employee_details/<int:id>/',views.employee_details,name='employee_details'),
    path('delete_employee/<int:id>/',views.employee_delete,name='employee_delete'),
    path('update_employee/<int:id>/',views.employee_update,name='employee_update'),
]

Employee/emp/models.py
from django.db import models

# Create a model named Employee with fields (name,age,salary,designation,place,image,department_name)
# Create your models here.
class Employee(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    salary = models.IntegerField()
    designation = models.CharField(max_length=50)
    place = models.CharField(max_length=100)
    image = models.ImageField(upload_to='employee')
    department_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

Employee/emp/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name','age','salary','designation','place','image','department_name']

Employee/emp/views.py
from django.shortcuts import render, redirect
from .models import Employee
from .forms import EmployeeForm


def employee_list(request):
    employee = Employee.objects.all()
    return render(request,'employee_list.html',{'employee':employee})

def employee_create(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('emp:employee_list')
    else:
        form = EmployeeForm()
    return render(request, 'employee_form.html', {'form': form})

def employee_details(request, id):
    employee = Employee.objects.get(id=id)
    return render(request,'employee_details.html',{'employee':employee})

def employee_delete(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('emp:employee_list')

def employee_update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST,request.FILES,instance=employee)
    if request.method == 'POST':
        form = EmployeeForm(request.POST,instance=employee)
        if form.is_valid():
            form.save()
            return redirect('emp:employee_list')
    else:
        form = EmployeeForm(instance=employee)
    return render(request,'employee_form.html',{'form':form})

Employee/templates/employee_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Employee</title>
</head>
<body>
<h2>Employee Details</h2>
<p><strong>Name:</strong> {{ employee.name }}</p>
<p><strong>Age:</strong> {{ employee.age }}</p>
<p><strong>Salary:</strong> {{ employee.salary }}</p>
<p><strong>Designation:</strong> {{ employee.designation }}</p>
<p><strong>Place:</strong> {{ employee.place }}</p>
<p><strong>Department_name</strong> {{ employee.department_name }}</p>
<img src="{{ employee.image.url }}" style="height: 150px;" alt="{{ employee.name }}">
</body>
</html>

Employee/templates/employee_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
</head>
<body>
<h2>Enter Details</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Submit</button>
</form>
</body>
</html>

Employee/templates/employee_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employees</title>
  <style>
  body {
    background-color: black;
    color: red;
}
  table {
    border: 1px solid black;
    width: 70%;
    margin: 20px auto;
    background-color: white;
  }
  th, td {
    border: 1px solid black;
    padding: 10px;
    text-align: left;
  }
    h1 {
    text-align: center;
    }
  </style>
</head>
<body>
<h1>Employee List</h1>
<button><a href="{% url 'emp:employee_create' %}">Add Employee</a></button>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Designation</th>
      <th>Place</th>
      <th>Department Name</th>
      <th>Image</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  {% for emp in employee %}
  <tr>
    <td>{{ emp.name }}</td>
    <td>{{ emp.age }}</td>
    <td>{{ emp.salary }}</td>
    <td>{{ emp.designation }}</td>
    <td>{{ emp.place }}</td>
    <td>{{ emp.department_name }}</td>
    <td><img src="{{ emp.image.url }}" height="200px;" width="150px;"></td>
    <td>
        <a href="{% url 'emp:employee_details' emp.id %}">Details</a><br>
        <a href="{% url 'emp:employee_update' emp.id %}">Edit</a><br>
        <a href="{% url 'emp:employee_delete' emp.id %}">Delete</a><br>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>

</body>
</html>